/* Second Brain OS V97 — publication diagnostics and safe update controls. */
'use strict';
(() => {
  const build=window.SecondBrainBuild||{major:97,label:'V97',cacheVersion:'v97-r1',criticalFiles:[]};
  const errors=[]; const MAX_ERRORS=30;
  const addError=(message,source='runtime')=>{const item={at:new Date().toISOString(),source,message:String(message||'Неизвестная ошибка').slice(0,1200)};errors.unshift(item);errors.splice(MAX_ERRORS);try{sessionStorage.setItem('secondBrainOS.v97.lastErrors',JSON.stringify(errors))}catch(_){}};
  window.addEventListener('error',event=>addError(event.error?.message||event.message,'window.error'));
  window.addEventListener('unhandledrejection',event=>addError(event.reason?.message||event.reason,'unhandledrejection'));

  const storageSummary=()=>{let state=null;let raw='';try{raw=localStorage.getItem('secondBrainOS.v1')||'';state=JSON.parse(raw||'null')}catch(_){}const counts={};if(state&&typeof state==='object')for(const [key,value] of Object.entries(state))if(Array.isArray(value))counts[key]=value.length;return{dataKeyPresent:raw!=='',bytes:new Blob([raw]).size,counts}};

  async function checkResources(){const files=build.criticalFiles||[];const results=[];for(const file of files){try{const response=await fetch(`${file}${file.includes('?')?'&':'?'}build=${encodeURIComponent(build.cacheVersion)}`,{cache:'no-store'});results.push({file,status:response.status,ok:response.ok,type:response.headers.get('content-type')||'',size:Number(response.headers.get('content-length')||0)});}catch(error){results.push({file,status:0,ok:false,error:error?.message||String(error)})}}return results}

  async function getPwaStatus(){if(!('serviceWorker'in navigator))return{supported:false};const registration=await navigator.serviceWorker.getRegistration().catch(()=>null);const cacheNames=await caches.keys().catch(()=>[]);return{supported:true,controlled:Boolean(navigator.serviceWorker.controller),registered:Boolean(registration),active:registration?.active?.scriptURL||'',waiting:Boolean(registration?.waiting),installing:Boolean(registration?.installing),cacheNames:cacheNames.filter(name=>name.startsWith('second-brain-os-'))}}

  async function report(){return{build,location:{href:location.href,standalone:matchMedia?.('(display-mode: standalone)')?.matches||navigator.standalone===true},storage:storageSummary(),backup:window.SecondBrainBackup?.getStatus?.()||null,cloud:window.SecondBrainCloud?.getStatus?.()||null,pwa:await getPwaStatus(),resources:await checkResources(),errors:[...errors]}}
  async function copyReport(){const text=JSON.stringify(await report(),null,2);try{await navigator.clipboard.writeText(text);window.SecondBrainApp?.toast?.('Технический отчёт скопирован')}catch(_){const blob=new Blob([text],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`second-brain-diagnostics-v${build.major}-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}}

  async function clearUiCache(){const prefix='second-brain-os-';const names=await caches.keys();await Promise.all(names.filter(name=>name.startsWith(prefix)).map(name=>caches.delete(name)));const registration=await navigator.serviceWorker?.getRegistration?.().catch(()=>null);await registration?.update?.().catch(()=>undefined);try{sessionStorage.setItem('secondBrainOS.v97.uiCacheCleared','1')}catch(_){}window.SecondBrainApp?.toast?.('Кэш интерфейса очищен. Данные сохранены.');setTimeout(()=>location.reload(),650)}
  async function checkUpdate(button){if(button){button.disabled=true;button.textContent='Проверяю…'}const results=await checkResources();const failed=results.filter(item=>!item.ok);if(button){button.disabled=false;button.textContent='Проверить файлы'}window.SecondBrainApp?.toast?.(failed.length?`Не загружено файлов: ${failed.length}`:'Все файлы V97 доступны');decorateSettings(true);return results}

  const statusText=(items)=>items.length&&items.every(item=>item.ok)?'Все файлы доступны':items.length?`${items.filter(item=>!item.ok).length} файлов недоступно`:'Не проверено';
  async function decorateSettings(force=false){const page=document.querySelector('.v78-page');if(!page||!/настройки/i.test(page.querySelector('h1')?.textContent||''))return;let card=page.querySelector('[data-v97-diagnostics]');if(card&&!force)return;const resources=await checkResources();const backup=window.SecondBrainBackup?.getStatus?.()||{};const pwa=await getPwaStatus();if(card)card.remove();card=document.createElement('section');card.className='v97-diagnostics-card';card.dataset.v97Diagnostics='true';card.innerHTML=`<header><div><small>ДИАГНОСТИКА ОБНОВЛЕНИЯ</small><h2>Версия, файлы и сохранность</h2><p>Проверка интерфейса не затрагивает финансы, задачи, привычки и другие записи.</p></div><span>${build.label}</span></header><div class="v97-diagnostics-grid"><article><small>Основной ключ данных</small><b>${localStorage.getItem('secondBrainOS.v1')!==null?'Сохранён':'Пока пуст'}</b></article><article><small>Резервная копия</small><b>${backup.createdAt?new Date(backup.createdAt).toLocaleString('ru-RU'):'Создаётся'}</b></article><article><small>Файлы сборки</small><b>${statusText(resources)}</b></article><article><small>Service Worker</small><b>${pwa.controlled?'Активен':pwa.registered?'Зарегистрирован':'Не активен'}</b></article></div><div class="v97-diagnostics-actions"><button type="button" data-v97-action="check-resources">Проверить файлы</button><button type="button" data-v97-action="clear-ui-cache">Обновить интерфейс без удаления данных</button><button type="button" data-v97-action="copy-diagnostics">Скопировать технический отчёт</button></div><details><summary>Проверенные файлы</summary><div class="v97-resource-list">${resources.map(item=>`<span class="${item.ok?'ok':'bad'}"><b>${item.ok?'✓':'!'}</b>${item.file}<em>${item.status||'ошибка'}</em></span>`).join('')}</div></details>`;page.appendChild(card)}

  document.addEventListener('click',event=>{const button=event.target.closest?.('[data-v97-action]');if(!button)return;const action=button.dataset.v97Action;if(action==='copy-diagnostics'){event.preventDefault();copyReport()}if(action==='clear-ui-cache'){event.preventDefault();if(confirm('Будет очищен только кэш интерфейса. Ваши записи, финансы, задачи и настройки останутся на месте.'))clearUiCache()}if(action==='check-resources'){event.preventDefault();checkUpdate(button)}});
  const observer=new MutationObserver(()=>requestAnimationFrame(()=>decorateSettings(false)));
  const start=()=>{observer.observe(document.documentElement,{childList:true,subtree:true});decorateSettings(false);document.documentElement.classList.add('sbos-v97-ready')};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.SecondBrainDiagnostics={report,copyReport,checkResources,clearUiCache,addError,getErrors:()=>[...errors]};
})();
